version: "3.8"
services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"