version: "3.8"
services:
  db:
    image: mariadb:12.0
    environment:
      - MYSQL_DATABASE=OnlineShoppingDB
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"